config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }
  root 'posts#index'
  get '/users/:id', to: 'users#show', as: 'user'
  resources :posts, only: %i(index new create show destroy) do
   resources :photos, only: %i(create)
   resources :likes, only: %i(create destroy)
   resources :comments, only: %i(create destroy)
 end

  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/thanks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { in: 1..160 }
  validates :email, presence: true
  validates :content, length: { maximum: 255 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
   validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :post
    validates :image, presence: true
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos
  def liked_by(current_user)
   Like.find_by(user_id: current_user.id, post_id: id)
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true
  validates :name, presence: true, length: { maximum: 50 }

  def update_without_current_password(params, *options)
   params.delete(:current_password)

   if params[:password].blank? && params[:password_confirmation].blank?
     params.delete(:password)
     params.delete(:password_confirmation)
   end

   result = update_attributes(params, *options)
   clean_up_passwords
   result
 end
end

app/models/video.rb
class Video < ApplicationRecord
  validates :vido, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
   @like = current_user.likes.build(like_params)
   @post = @like.post
   if @like.save
     respond_to :js
   end
 end

 def destroy
   @like = Like.find_by(id: params[:id])
   @post = @like.post
   if @like.destroy
     respond_to :js
   end
 end

 private
   def like_params
     params.permit(:post_id)
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy)

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
   @post = Post.new(post_params)
   if @post.photos.present?
     @post.save
     redirect_to root_path
     flash[:notice] = "投稿が保存されました"
   else
     redirect_to root_path
     flash[:alert] = "投稿に失敗しました"
   end
 end

 def index
    @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
 end

 def show
 end

 def destroy
   if @post.user == current_user
     flash[:notice] = "投稿が削除されました" if @post.destroy
   else
     flash[:alert] = "投稿の削除に失敗しました"
   end
   redirect_to root_path
 end

 private
 def post_params
     params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
 end

 def set_post
      @post = Post.find_by(id: params[:id])
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
   return user.profile_photo unless user.profile_photo.nil?
   gravatar_id = Digest::MD5::hexdigest(user.email).downcase
   "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div id="wrapper">
          <%= render 'partial/navbar' if current_user %>

          <% if flash[:notice] %>
            <div class="alert alert-info"><%= flash[:notice] %></div>
          <% end %>
          <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% end %>
          
          <div class="container">
        <%= yield %>
      <%= render 'partial/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>ページ</h1>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Instagram_app

      </p>
    </div>
  </div>
</footer>

app/views/partial/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>  
  </div>
</nav>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center">
        <li>
          <%= link_to "投稿", new_post_path, class: "btn btn-primary" %>
        </li>
        <li>
        <%= link_to "動画投稿",  "ルートパス", class: "btn btn-primary" %>
        </li>
        <li>
          <%= link_to "お問い合わせ", inquiries_new_path, class: "btn btn-primary" %>
        </li>
        <li>
          <%= link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
        </li>
      </ul>
    </div>
  </div>
</nav>